spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devblind_local_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

sms:
  enabled: false  # 로컬 환경에서는 SMS 발송 비활성화
  provider: fake
  ncp:
    access-key: dummy
    secret-key: dummy
    service-id: dummy
    sender-phone: dummy

firebase:
  enabled: false  # 로컬 환경에서는 Firebase 비활성화
