# 개발 환경 설정
# 실제 개발 서버 배포 시 환경변수로 설정 필요
spring:
  datasource:
    url: jdbc:postgresql://dev-host:5432/devdb
    driver-class-name: org.postgresql.Driver
    username: dev_user
    password: dev_password
    hikari:
      maximum-pool-size: 20

    data:
      redis:
        host: localhost
        port: 6379
        password: redis6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

sms:
  enabled: true
  provider: ncp
  ncp:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    service-id: ${NCP_SERVICE_ID}
    sender-phone: ${NCP_SENDER_PHONE}
