spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devblind_local_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

# 로컬 환경에서만 필요한 설정들
sms:
  enabled: false  # 로컬 환경에서는 SMS 발송 비활성화
  provider: fake
  ncp:
    access-key: dummy
    secret-key: dummy
    service-id: dummy
    sender-phone: dummy

firebase:
  enabled: false  # 로컬 환경에서는 Firebase 비활성화

# 로컬 환경에서 환경변수가 없을 때 사용할 기본값
jwt:
  secret: local_dev_secret_key_for_development_only

toss:
  payment:
    secret-key: local_test_key
  refund:
    secret-key: local_test_key

aws:
  s3:
    bucket: devblind-local-bucket
    access-key: local_access_key
    secret-key: local_secret_key
